version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'PESSOA'
      MYSQL_USER: 'pessoa'
      MYSQL_PASSWORD: 'pessoa'
      MYSQL_ROOT_PASSWORD: 'pessoa'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
